---
apiVersion: v1
kind: Namespace
metadata:
  name: personal-website-development
  annotations:
    field.cattle.io/projectId: c-s7tqh:p-b28xd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: personal-website
  namespace: personal-website-development
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      hostAliases:
        - hostnames:
          - testhub.online
          ip: 35.225.145.109
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: personal-website
        image: ${CICD_REGISTRY}/personal-website:latest
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: personal-website
  namespace: personal-website-development
  labels:
    app: personal-website
spec:
  selector:
    app: personal-website
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: personal-website
  namespace: personal-website-development
spec:
  rules:
  - host: testhub.online
    http:
      paths:
      - backend:
          serviceName: personal-website
          servicePort: 8080